# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.sandbox_set_position_balance_request import SandboxSetPositionBalanceRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestSandboxSetPositionBalanceRequest(unittest.TestCase):
    """SandboxSetPositionBalanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSandboxSetPositionBalanceRequest(self):
        """Test SandboxSetPositionBalanceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sandbox_set_position_balance_request.SandboxSetPositionBalanceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
