# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.currency_position import CurrencyPosition  # noqa: E501
from swagger_client.rest import ApiException


class TestCurrencyPosition(unittest.TestCase):
    """CurrencyPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrencyPosition(self):
        """Test CurrencyPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.currency_position.CurrencyPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
