# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.placed_limit_order import PlacedLimitOrder  # noqa: E501
from swagger_client.rest import ApiException


class TestPlacedLimitOrder(unittest.TestCase):
    """PlacedLimitOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacedLimitOrder(self):
        """Test PlacedLimitOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.placed_limit_order.PlacedLimitOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
