# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_cancel_post(self):
        """Test case for orders_cancel_post

        Отмена заявки  # noqa: E501
        """
        pass

    def test_orders_get(self):
        """Test case for orders_get

        Получение списка активных заявок  # noqa: E501
        """
        pass

    def test_orders_limit_order_post(self):
        """Test case for orders_limit_order_post

        Создание лимитной заявки  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
