# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tinkoff_api_client
from models.operation_type import OperationType  # noqa: E501
from tinkoff_api_client.rest import ApiException


class TestOperationType(unittest.TestCase):
    """OperationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationType(self):
        """Test OperationType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tinkoff_api_client.models.operation_type.OperationType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
