# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tinkoff_api_client
from api.portfolio_api import PortfolioApi  # noqa: E501
from tinkoff_api_client.rest import ApiException


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self):
        self.api = api.portfolio_api.PortfolioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_portfolio_currencies_get(self):
        """Test case for portfolio_currencies_get

        Получение валютных активов клиента  # noqa: E501
        """
        pass

    def test_portfolio_get(self):
        """Test case for portfolio_get

        Получение портфеля клиента  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
