# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.portfolio_position import PortfolioPosition  # noqa: E501
from swagger_client.rest import ApiException


class TestPortfolioPosition(unittest.TestCase):
    """PortfolioPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortfolioPosition(self):
        """Test PortfolioPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.portfolio_position.PortfolioPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
