# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.orders_response import OrdersResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersResponse(unittest.TestCase):
    """OrdersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrdersResponse(self):
        """Test OrdersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.orders_response.OrdersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
